# Generated by Django 5.0 on 2023-12-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Leave', 'Leave')], default='Active', max_length=100),
        ),
    ]
